#!/usr/bin/env bash
#  displays numbers from 1 to 100.

for ((k=1; k<=100; k++));
	do
	if ((k % 5 == 0)) && ((k % 3 == 0));
		then
		echo "FizzBuzz";
	elif ((k % 3 == 0));
		then
		echo "Fizz";
	elif ((k % 5 == 0));
		then
		echo "Buzz";
	else
		echo $k;
	fi;
done;
